Hanna Shestak: Homework_4 completed
eugene-okulik/annshestan pull request #3
Opened 2024-10-31 19:13 UTC by annshestak

2024-11-01 11:59 UTC, eugene-okulik requested changes
Всё отлично, но проверочку на внимательность не прошла ))

2024-11-01 11:59 UTC, eugene-okulik commented on homework/anna_shestak/Homework_4/Task.py
> +ddict['i am tuple'] = 'three'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-11-01 19:23 UTC, annshestak commented on homework/anna_shestak/Homework_4/Task.py
> +ddict['i am tuple'] = 'three'
точно) исправила

2024-11-02 10:05 UTC, eugene-okulik approved these changes
:+1:

2024-11-02 10:05 UTC, merged