Hanna Shestak: Homework_5 completed
eugene-okulik/annshestan pull request #4
Opened 2024-11-10 09:13 UTC by annshestak

2024-11-11 06:42 UTC, eugene-okulik requested changes

2024-11-11 06:42 UTC, eugene-okulik commented on homework/anna_shestak/Homework_5/Task 2.py
> +result_1 = str_1.index('42')
Если еще в момент написания программы мы знаем, что в строке будет число 42, то мы можем написать просто print(42 + 10)  
Заморочка в том, чтобы найти в этой строке число, каким бы оно там ни было. Для этого нужно найти в этих строках что-то одинаковое: количество символов перед числом разное; количество символов в числе тоже разное. Но есть в структуре всех строк что-то одинаковое и на это можно опереться.  
В примерах - варианты того, как может ответить программа. Вместо числа 42 может оказаться число 28346473, вместо 514 число 3. Нам нужно сделать один код, который сможет работать с любым из вариантов ответа. То есть обработать каждую переменную абсолютно одинаковым кодом. Пока что делаем это копируя код, потом будем учиться как избежать здесь этого копирования.

2024-12-01 08:59 UTC, annshestak commented on homework/anna_shestak/Homework_5/Task 2.py
> +result_1 = str_1.index('42')
Исправила!
Был долгий перерыв, вижу плашку Outdated - она на что-то влияет? Нужн дополнительные действия с моей стороны?

2024-12-01 09:43 UTC, eugene-okulik approved these changes
:+1:

2024-12-01 09:43 UTC, merged